
class CSSSelector_mall:
    NAME = '.qaNIZv'    
    AVG_RATING = '._3Oj5_n._2z6cUg'
    N_REVIEWS = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div.product-briefing.flex.card._2cRTS4 > div.flex.flex-auto.k-mj2F > div > div.flex._32fuIU > div:nth-child(2) > div._3Oj5_n'
    N_LOVED = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div.product-briefing.flex.card._2cRTS4 > div._30iQ1- > div.flex.justify-center.items-center > div.flex.items-center._25DJo1'
    RATE_5 = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div:nth-child(2)'
    RATE_4 = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div:nth-child(3)'
    RATE_3 = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div:nth-child(4)'
    RATE_2 = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div:nth-child(5)'
    RATE_1 = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div:nth-child(6)'
    RATE_WITH_CMT = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div.product-rating-overview__filter.product-rating-overview__filter--with-comment'
    RATE_WITH_IMGVID = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div.product-rating-overview__filter.product-rating-overview__filter--with-photo'
    SHOP_NAME = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div._1zBnTu.page-product__shop > div._1Sw6Er > div > div._3Lybjn'
    SHOP_N_REVIEW = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div._1zBnTu.page-product__shop > div._3mK1I2 > div:nth-child(1) > div > span'
    SHOP_N_PRODUCT = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div._1zBnTu.page-product__shop > div._3mK1I2 > div:nth-child(1) > a > span'
    SHOP_RATE_FEEDBACK = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div._1zBnTu.page-product__shop > div._3mK1I2 > div:nth-child(2) > div:nth-child(1) > span'
    SHOP_AGE = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div._1zBnTu.page-product__shop > div._3mK1I2 > div:nth-child(3) > div:nth-child(1) > span'
    SHOP_FOLLOWER = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div._1zBnTu.page-product__shop > div._3mK1I2 > div:nth-child(3) > div:nth-child(2) > span'
    SHOP_TIME_FEEDBACK = '#main > div > div._1Bj1VS > div.page-product.page-product--mall > div.container > div:nth-child(3) > div._1zBnTu.page-product__shop > div._3mK1I2 > div:nth-child(2) > div:nth-child(2) > span'

    

class CSSSelector:
    NAME = '.qaNIZv'    
    AVG_RATING = '._3Oj5_n._2z6cUg'
    N_REVIEWS = 'div.product-briefing.flex.card._2cRTS4 > div.flex.flex-auto.k-mj2F > div > div.flex._32fuIU > div:nth-child(2) > div._3Oj5_n'
    PRICE = 'div.flex.items-center > div._3n5NQx'
    N_SOLD = 'div.product-briefing.flex.card._2cRTS4 > div.flex.flex-auto.k-mj2F > div > div.flex._32fuIU > div.flex.SbDIui > div._22sp0A'
    N_LOVED = 'div.product-briefing.flex.card._2cRTS4 > div._30iQ1- > div.flex.justify-center.items-center > div.flex.items-center._25DJo1'
    RATE_5 = 'div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div:nth-child(2)'
    RATE_4 = 'div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div:nth-child(3)'
    RATE_3 = 'div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div:nth-child(4)'
    RATE_2 = 'div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div:nth-child(5)'
    RATE_1 = 'div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div:nth-child(6)'
    RATE_WITH_CMT = 'div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div.product-rating-overview__filter.product-rating-overview__filter--with-comment'
    RATE_WITH_IMGVID = 'div.page-product__content > div.page-product__content--left > div:nth-child(2) > div > div.product-rating-overview > div.product-rating-overview__filters > div.product-rating-overview__filter.product-rating-overview__filter--with-photo'
    SHOP_NAME = 'div._1zBnTu.page-product__shop > div._1Sw6Er > div > div._3Lybjn'
    SHOP_N_REVIEW = 'div._1zBnTu.page-product__shop > div._3mK1I2 > div:nth-child(1) > div > span'
    SHOP_N_PRODUCT = 'div._1zBnTu.page-product__shop > div._3mK1I2 > div:nth-child(1) > a > span'
    SHOP_RATE_FEEDBACK = 'div._1zBnTu.page-product__shop > div._3mK1I2 > div:nth-child(2) > div:nth-child(1) > span'
    SHOP_AGE = 'div._1zBnTu.page-product__shop > div._3mK1I2 > div:nth-child(3) > div:nth-child(1) > span'
    SHOP_FOLLOWER = 'div._1zBnTu.page-product__shop > div._3mK1I2 > div:nth-child(3) > div:nth-child(2) > span'
    SHOP_TIME_FEEDBACK = 'div._1zBnTu.page-product__shop > div._3mK1I2 > div:nth-child(2) > div:nth-child(2) > span'
    CMT_LIST = 'div > div.product-ratings__list > div.shopee-product-comment-list > .shopee-product-rating'
    
    CMT_CONTENT = '.shopee-product-rating__content'
    CMT_RATING = '.shopee-product-rating__rating'
    CMT_STAR_ACTIVE = '.icon-rating-solid--active'
